# Generated by Django 5.2.15 on 2026-06-09 20:01

import django.core.validators
import django.db.models.deletion
import web_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_seed_default_counting_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppStatuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_camera_heartbeat', models.DateTimeField(default=None, null=True)),
                ('last_api_delivery_attempt', models.DateTimeField(default=None, null=True)),
                ('last_api_delivery_success', models.DateTimeField(default=None, null=True)),
                ('last_video_recording_start', models.DateTimeField(default=None, null=True)),
                ('last_video_recording_stop', models.DateTimeField(default=None, null=True)),
                ('last_pleople_count_event', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CountingLines',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('offset', models.DecimalField(decimal_places=1, default=0.1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('points', models.JSONField(blank=True, default=web_app.models.default_counting_line_points, validators=[web_app.models.validate_counting_line_points])),
                ('entrance_number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('in_direction_sign', models.IntegerField(choices=[(-1, '-1'), (1, '1')])),
            ],
        ),
        migrations.CreateModel(
            name='RuntimeParametrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('are_people_burred_in_videos', models.BooleanField(default=True)),
                ('api_delivery_url', models.URLField(blank=True)),
                ('api_delivery_enabled', models.BooleanField(default=False)),
                ('api_delivery_auth_token', models.CharField(blank=True, max_length=255)),
                ('api_delivery_interval', models.IntegerField(default=60, help_text='in seconds')),
                ('api_delivery_lookback_window', models.IntegerField(default=60, help_text='in minutes')),
                ('system_timezone', models.CharField(default='UTC', max_length=150)),
                ('store_code', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PleopleCountEvents',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('in', 'in'), ('out', 'out')], max_length=10)),
                ('confidence', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('tracklet_id', models.CharField(max_length=100, validators=[django.core.validators.MinValueValidator(0)])),
                ('entrance_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('counting_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.countinglines')),
            ],
        ),
    ]
